version: '3.9'

services:
  development:
    build:
      args:
        UID: ${UID}
        GID: ${GID}
        USER: ${USER}
        REPO: ${REPO}
      context: .
      dockerfile: Dockerfile
    command: bash -c "bash"
    container_name: ${USER}-${REPO}-dev
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TERM=xterm-256color
    extra_hosts:
      - ${REPO}-dev:127.0.0.1
    hostname: ${REPO}-dev
    image: ${REPO}-dev:latest
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
      - ~/.ssh:${HOME}/.ssh:ro
      - ~/.gitconfig:${HOME}/.gitconfig:ro
      - ${PWD}:${HOME}/ws/src/${REPO}
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    working_dir: ${HOME}/ws
